// Generated by Wrangler by running `wrangler types`

interface Env {
	SECRET_TELEGRAM_API_TOKEN: string;
	GEMINI_API_KEY: string;
	account_id: string;
	cf_ai_gateway_name: string;
	DB: D1Database;
	api_psk: string;
}
